### ISSUE TITLE
Clarification Request: Risks with Consensus Participants 

### ISSUE THREAD

**Issue by foundingnimo** [votem/proof-of-vote#8]
Page 20
The risk posed by Trustee collusions with regard to voter anonymity is discussed earlier (page 19). However - there is a risk with consensus participants collusion where transactions may be dropped arbitrarily or after a fashion. As identified in figure 2 - the consensus participants have less governance characteristics - but as currently written - it seems like they may have the ability to interfere with smooth running and while may not necessarily be able to change results - may be able to reject a significant enough number of votes if collusion/defect is introduced.

**Comment by phayes** [comment]
You are essentially correct.  If 1/3 of consensus nodes collude (1/3 of the voting power specifically), they can prevent votes from making it onto the chain.  

We had originally included a discussion of this in an earlier version of the paper but elided it to keep the paper shorter.  I’ll try to add some of it back in.   

Salient highlights: 

1. Such collusion is very visible, and would result in detection, investigation, and ultimately banishment of misbehaving nodes.  This can even be partially automated. 

2. Not all nodes need to have the same voting power in the consensus algorithm.  An election authority may choose to assign consensus voting power based on governance and certification levels that the participatzing node has undergone.  This allows an election authority to open participation to a wide number of nodes, but also manage risk in a fine-grained manner.

**Comment by jeffreypstern** [comment]
@phayes added node collusion discussion to the whitepaper.
